# Generated by Django 4.1.2 on 2022-11-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('nro_cliente', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruta', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('nro_articulo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vegetal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegetal', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('nro_articulo', models.IntegerField()),
            ],
        ),
    ]
